name: Deploy to Freehostia

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Portfolio to Freehostia
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy to Freehostia
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          server-dir: /www/ratankumar.com/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
